version: "3"
services:
  app:
    build: .
    ports: ['4000:80', '5000:6379']
    volumes: 
         - le-vin-coupe-sync:/app/src:nocopy # set nocopy

volumes:
  le-vin-coupe-sync:
    external: true